# Form implementation generated from reading ui file 'mainpanel.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Youtube Dowloader")
        MainWindow.resize(631, 244)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.url = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget)
        self.url.setObjectName("url")
        self.horizontalLayout.addWidget(self.url)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 110, 181, 34))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 110, 191, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.contenedorbtn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.contenedorbtn.setContentsMargins(0, 0, 0, 0)
        self.contenedorbtn.setObjectName("contenedorbtn")
        self.buttonmp4 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.buttonmp4.setObjectName("buttonmp4")
        self.contenedorbtn.addWidget(self.buttonmp4)
        self.buttonmp3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.buttonmp3.setObjectName("buttonmp3")
        self.contenedorbtn.addWidget(self.buttonmp3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Dowloader"))
        self.label.setText(_translate("MainWindow", "Enlace de Youtube:"))
        self.pushButton.setText(_translate("MainWindow", "Seleccionar ruta"))
        self.buttonmp4.setText(_translate("MainWindow", "Descargar MP4"))
        self.buttonmp3.setText(_translate("MainWindow", "Descargar MP3"))
